services:
  client:
    container_name: finance_client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/index.html:/app/index.html
      - ./client/vite.config.ts:/app/vite.config.ts
      - ./client/tailwind.config.js:/app/tailwind.config.js
      - ./client/tsconfig.json:/app/tsconfig.json
      - ./client/tsconfig.app.json:/app/tsconfig.app.json
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped

  api:
    container_name: finance_api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8080"
    volumes:
      - ./api/src:/app/src
    env_file:
      - ./api/.env
    environment:
      PG_DB: finance
      PG_USER: financeUser
      PG_PASSWORD: finance1!
      PG_HOST: finance_db
      TZ: America/Denver
    depends_on:
      finance_db:
        condition: service_healthy
    restart: unless-stopped

  finance_db:
    image: postgres:17-alpine
    container_name: finance_db
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: financeUser
      POSTGRES_PASSWORD: finance1!
      TZ: America/Denver
    ports:
      - "5432:5432"
    volumes:
      - ./api/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financeUser -d finance"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
