apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finance-api-ingress
  namespace: finance-bot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - finance-jesus.duckdns.org
    secretName: finance-api-tls
  rules:
  - host: finance-jesus.duckdns.org
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: finance-api
            port:
              number: 8080
